/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;

import lombok.extern.log4j.Log4j2;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@Log4j2
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
    log.info("Congrats! Your XMeme Application server has started");

  }
}
